# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

# 3 nov 2022: configuració seguint les indiciacions d'aquí: https://rasa.com/docs/rasa/chitchat-faqs/
# 24 nov: retocada a partir d'aquí: https://learning.rasa.com/conversational-ai-with-rasa/pipeline/

language: ca

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model (seguint les recomanacions per a SpaCy) for more information.

  - name: SpacyNLP
    #model: "ca_core_news_lg"
    model: "ca_bsc_demo_trf"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    "pooling": "mean" # pot ser mean o pot ser max
  - name: RegexFeaturizer
  #- name: LexicalSyntacticFeaturizer
    #"features": [
        #[],
        #["pos", "BOS", "EOS", "low", "upper", "title", "digit"],
        #[],
    #]
    # que tingui en compte el pos per a trobar les entities
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier        # "DIET (Dual Intent and Entity Transformer) is a multi-task architecture for intent classification and entity recognition. [...] DIET does not provide pre-trained word embeddings or pre-trained language models but it is able to use these features if they are added to the pipeline."
    epochs: 100
  #  entity_recognition: False   # es pot desactivar
  - name: "SpacyEntityExtractor"
    # dimensions to extract
    dimensions: ["PER", "LOC", "ORG", "MISC"]
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.60
    ambiguity_threshold: 0.1


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy 
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
