version: '3.9'
services:
  tts-api:
    restart: unless-stopped
    image: "bsctemu/aina-tts-api:cache-dev1.0"
    expose:
      - "8000"
  stt-server:
    restart: unless-stopped
    image: "assistent/kaldi-catala:0.0.4"
    expose:
      - "5001"
  rasa:
    restart: unless-stopped
    image: "bsctemu/aina-minibot:1.0.6"
    ports:
      - "5005:5005"
    command: run --credentials credentials.yml --model latest-model.tar.gz --endpoints endpoints.yml --debug
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
    environment:
      - VOSK_SERVER_HOST=stt-server
      - VOSK_SERVER_PORT=5001
    depends_on:
      - stt-server
      - tts-api
  rasa-actions:
    restart: unless-stopped
    image: "bsctemu/aina-minibot-custom-actions-server:0.0.8"
    expose:
      - "5055"
    depends_on:
      - rasa
  interface:
    restart: unless-stopped
    image: "bsctemu/aina-minibot-interface:1.0.3"
    ports:
      - "8004:80"
    depends_on:
      - rasa