version: '3.9'
services:

  tts-api:
    image: projecteaina/tts-api:ce37a21ac6c8bab163c26722f6f988d696af37d2
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - minibot-network
    environment:
      - SPEECH_SPEED=${TTS_SPEECH_SPEED}
      - MP_WORKERS=${TTS_MP_WORKERS}
    shm_size: ${TTS_SHM_SIZE}
    deploy:
      resources:
        limits:
          memory: ${TTS_MEM_LIMIT}

  stt-server:
    restart: unless-stopped
    image: "assistent/kaldi-catala:0.0.4"
    expose:
      - "5001"
    networks:
      - minibot-network
    deploy:
      resources:
        limits:
          memory: ${STT_MEM_LIMIT}

  rasa:
    container_name: minibot-rasa
    build: 
      context: .
    restart: unless-stopped
    expose:
      - "5005"
    networks:
      - proxy-net
      - minibot-network
    command: run --credentials credentials.yml --model ./models --endpoints endpoints.yml --debug
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
    environment:
      - VOSK_SERVER_HOST=stt-server
      - VOSK_SERVER_PORT=5001
    depends_on:
      - stt-server
      - tts-api

  rasa-actions:
    container_name: minibot-rasa-actions
    build: 
      context: ./actions
    restart: unless-stopped
    expose:
      - "5055"
    networks:
      - minibot-network
    depends_on:
      - rasa
      
  interface:
    restart: unless-stopped
    container_name: rasa-voice-interface
    build:
      context: ./rasa-voice-interface
      dockerfile: docker/Dockerfile
    environment:
      - VUE_RASA_APP_PUBLIC_URL=${VUE_RASA_APP_PUBLIC_URL}
    expose:
      - "80"
    networks:
      - proxy-net
    depends_on:
      - rasa
      - rasa-actions


networks:
  proxy-net:
    external: true
    name: proxy-net
  minibot-network:
